### PR TITLE
Remove a few buffer allocations

### PR DESCRIPTION
**Pull request by ocoanet**
I removed the allocations from the the send and receive paths. There are no unit tests and I cannot run the program so I tried to make as few changes as possible. Still this PR should be treated with the level of confidence of experimental code.

It would be nice if the program could be tested on real hardware. I might try to get real hardware myself if I need to propose more changes :).

It should solve #1.

### CODE REVIEW

**Comment by emmericp** [comment]
This patch unfortunately slows it down a little bit which is somewhat counter-intuitive. The slow-down is barely measurable (~0.5 - 1%) but statistically significant :(

**Comment by ocoanet** [comment]
Interesting. I guess that the changes prevent the JIT from removing bound checks in a few places. I will switch to .NET Core 2.1 to use Span and I will create a few benchmarks to make sure the new code is faster.

**Comment by ocoanet** [comment]
I just updated the patch. The project now targets .NET Core 2.1. I replaced array usage by spans in multiple places. I could not benchmark all the changes but I was able to measure a performance boost in a couple of methods.

I hope this fixes the slow-down.

Just in case, could you send me a link to a network card I could use to run the performance tests?
Also, could you give the the specs of the machine and OS you use for those tests?

**Comment by emmericp** [comment]
Thanks, this is measurably faster... by about 1% ;) I guess the bottleneck is somewhere else

Any ixgbe NIC will do, we are running on NICs based on the Intel 82599 chip (NICs sold by many vendors, we are using Intel X520 and Supermicro onboard NICs). But Intel X540 or X550 also works.

The machine running the benchmarks is an Xeon E5-2620 v3 @ 2.40GH (turbo boost disabled) with Debian stretch

**Comment by ocoanet** [comment]
The goal of this PR was not to significantly reduce the average latency but to improve the latency distribution by removing GC pauses. Feel free to close it if you do not measure any progression in this regard.

I have a few change ideas to improve the average latency but I need to be able to run the performance tests myself to try them. However, I do not expect to find major improvements!

**Comment by emmericp** [comment]
I've indeed wanted to have another look at the latency here because C# is by far the worst offender when it comes to tail latency.

My current plan was mainly to try to set the GC to SustainedLowLatency, but I'll also test if your patch changes anything

**Comment by emmericp** [comment]
Here are some quick and dirty latency measurements when loaded with 10 Mpps

csharp-latency

The SustainedLowLatency GC mode really helps but costs around 1% performance, so it's now as fast as it was before with your patch and the GC change.


It sometimes eats some packets during startup, it feels like this happens more often with this PR but I'm not sure (would require way more measurements). Probably due to JIT compilation, but given the tiny code size it really shouldn't *drop* packets as that would imply a pause of several milliseconds. Sometimes it doesn't happen at all

**Comment by emmericp** [comment]
Compared to C, Rust, and Go with the same workload:

latency-comparison-10mpps

**Comment by ocoanet** [comment]
Thank you for the detailed reports. My opinion is that for such a low level component, all heap allocations should be removed. SustainedLowLatency is an interesting option but in my view it should not be required because there should not be any GC work.

I will try to remove the remaining allocations. Are you using `PrintStatsDiff` in your performance tests? If `PrintStatsDiff` is required, I can try to rewrite it without allocations. If not, I suggest to use [HdrHistogram](https://www.nuget.org/packages/HdrHistogram/) instead.

**Comment by emmericp** [comment]
Rotate the graphs by 90° counter clockwise, replace the labels and you got an hdr histogram ;)

Maximum latency is basically the same as the 99.9999th percentile here; graphs are based on timestamps of all packets in a 10 second timeframe using fiber optic splitters.

I'll add the hdr hist style graphs to https://github.com/ixy-languages/ixy-languages later. The ccdf variant is more common in an academic setting: we are currently working on a paper in which these graphs will be used.


Yes, we are running the full stats including printing to stdout; this is one of the reasons why there's some tail latency even in C and Rust (the other being local timer interrupts that even seem to happen with isolcpus). Goal here isn't to be *completely* allocation-free as a realistic use case would build something on top of it potentially causing some allocations.

**Pull request merged**
